# Generated by Django 4.2.7 on 2024-02-18 17:11

from django.db import migrations, models
import django_extensions.db.fields
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Tag name', max_length=50)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Blog post title', max_length=255)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(help_text='Post content')),
                ('description', models.TextField(default='No description for this post', help_text='Post description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'], unique=True)),
                ('tags', models.ManyToManyField(help_text='Tags for the blog post', related_name='posts', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-date_posted'],
            },
        ),
    ]
