# Generated by Django 4.2.7 on 2023-11-16 20:09

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(help_text="Author's first name", max_length=50)),
                ('last_name', models.CharField(help_text="Author's last name", max_length=50)),
                ('misc_info', models.TextField(help_text='Miscellaneous information about the author', max_length=500)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['first_name', 'last_name'])),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Recipe name', max_length=70, unique=True)),
                ('category', models.CharField(default='Uncategorized', help_text='Recipe category', max_length=50)),
                ('ingredients', models.TextField(help_text='Ingredients required for the recipe', max_length=2000)),
                ('instructions', models.TextField(help_text='Cooking instructions for the recipe', max_length=2000)),
                ('misc_info', models.TextField(help_text='Miscellaneous information about the recipe', max_length=500)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'], unique=True)),
                ('author', models.ForeignKey(help_text='Author of the recipe', on_delete=django.db.models.deletion.CASCADE, to='cookbook.author')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
