# Generated by Django 4.2.6 on 2023-11-16 06:39

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(help_text="Author's first name", max_length=50)),
                ('last_name', models.CharField(help_text="Author's last name", max_length=50)),
                ('misc_info', models.TextField(help_text='Miscellaneous information about the author', max_length=500)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield-djangodbmodelsfieldscharfield', editable=False)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Recipe name', max_length=70, unique=True)),
                ('misc_info', models.TextField(help_text='Miscellaneous information about the recipe', max_length=500)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', editable=False, max_length=80)),
                ('author', models.ForeignKey(help_text='Author of the recipe', on_delete=django.db.models.deletion.CASCADE, to='cookbook.author')),
            ],
            options={
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
            },
        ),
    ]
