# Generated by Django 4.2.7 on 2023-11-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serving_size',
            field=models.CharField(default='None listed', help_text='Serving size for the recipe', max_length=100),
        ),
    ]
