# Generated by Django 4.2.7 on 2023-11-29 07:01

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_recipe_serving_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['first_name', 'last_name'], unique=True),
        ),
    ]
